# Tuning for the Heron PID controller.

fwd_vel:
  kf: 10
  kp: 200
  ki: 0.0
  kd: 20
  imax: 0
  imin: 0

yaw_rate:
  kf: 0.0
  kp: 150
  ki: 0.0 # 30
  kd: 10.0 # 30
  imax: 0.0
  imin: 0.0

yaw:
  kf: 5
  kp: 0.3
  ki: 0.0
  kd: 0.1
  imax: 5.0
  imin: -5.0

max:
  fwd_vel: 3.0
  bck_vel: 0.5

twist_cmd:
  timeout: 1.5
